version: '3.9'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.config:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - streamlit
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
